name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Executing every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run stats script
        env:
          GH_TOKEN: ${{ secrets.STATS_TOKEN }}
        run: python fetch_stats.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Move the generated stats file to a temporary location
          mv github_full_stats.json /tmp/github_full_stats.json

          # Fetch the existing 'data' branch to ensure we have the latest changes
          git fetch origin data
          git checkout data || git checkout --orphan data

          # Move the generated stats file to the root of the repository
          mv /tmp/github_full_stats.json .

          # Move the generated stats file to the root of the repository
          git add github_full_stats.json

          # Commit changes if there are any, otherwise exit without error
          git commit -m "Update Github stats" || exit 0

          # Push the changes to the 'data' branch, force updating it
          git push origin HEAD:data --force
