name: Update Waka Chart

on:
  schedule:
    - cron: '0 */12 * * *' # Executing every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch All-Time WakaTime Data
        env:
          WAKA_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          AUTH=$(echo -n "$WAKA_KEY" | base64)
          
          curl -H "Authorization: Basic $AUTH" \
          "https://wakatime.com/api/v1/users/current/stats/all_time" \
          -o wakatime-chart.json

      - name: Commit and Push JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Move the generated stats file to a temporary location
          mv wakatime-chart.json /tmp/wakatime-chart.json

          # Fetch the existing 'data' branch to ensure we have the latest changes
          git fetch origin data
          git checkout data || git checkout --orphan data

          # Move the generated stats file to the root of the repository
          mv /tmp/wakatime-chart.json .

          # Move the generated stats file to the root of the repository
          git add wakatime-chart.json

          # Commit changes if there are any, otherwise exit without error
          git commit -m "Update WakaTime chart data" || exit 0

          # Push the changes to the 'data' branch, force updating it
          git push origin HEAD:data --force
